### ISSUE TITLE
Нет работающего приложения

### ISSUE THREAD

**Issue by BackBunnys** [polar-sky/vetclinic#10]
Подскажите, пожалуйста, как я могу кастрировать своего котика?
Не могу найти ссылку на ваше работающее приложение.

P.S.: мой котик на аве, не подскажите, сколько будет стоить?

**Comment by Inu07040** [comment]
ПАШОЛ ТЫ

**Comment by Inu07040** [comment]
(скачайте приложение и сами закострируйтесь)

**Comment by Inu07040** [comment]
@BackBunnys накрутчиватель мда :/

**Comment by polar-sky** [comment]
@Inu07040 @BackBunnys Спасибо за обращение, простите за несколько грубый ответ моей коллеги. Позвольте сгладить нашу вину - дарим Вам кэшбек 5% на кастрацию с 27.06 по 28.06, забрать подарок можно по ссылке [КЭШБЕК](https://www.youtube.com/watch?v=o47NEsDm2gw)

**Comment by BackBunnys** [comment]
Добрый день, @polar-sky. Как я могу активировать промо-код на 5%-ый кэшбек? Ваш cumлега @Inu07040 всё ещё не предоставил ссылку на работающее приложение.

P.S.: было бы неплохо побыстрей кастрировать котика. Как вы наверняка увидели по аве, ему очень плохо.

**Comment by Inu07040** [comment]
@BackBunnys, сказали же, по ссылке перейти *хатьфу*

**Comment by BackBunnys** [comment]
Добрый день, @Inu07040. Вы, наверняка, не поняли смысл написанного. Прошу вас ещё раз перечитать наш с @polar-sky диалог. 
По ссылке я перешёл - промокод на кэшбек получил. Как я могу его активировать?

Прошу поторопиться с решением данной проблемы. За время ожидания мой котик поседел от испытываемых мук.
![image](https://user-images.githubusercontent.com/53627087/176121034-0e8dbf81-16f1-4926-8f62-19026761c013.png)

**Comment by Inu07040** [comment]
@BackBunnys, советую вам кастрировать его самому. Вы обязательно с этим справитесь!

**Comment by BackBunnys** [comment]
Котик умер X﹏X

**Comment by Inu07040** [comment]
@BackBunnys, соболезнуем вашей утрате. ждем вас у нас снова с живым котом!
